# ship the fastapi metrics, traces, and logs to AWS using OpenTelemetry Collector

services:

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      OTEL_PYTHON_LOG_CORRELATION: "true"
      # OTEL_PYTHON_LOGGING_AUTO_INSTRUMENTATION_ENABLED: "true"
      OTEL_PYTHON_LOG_LEVEL: "INFO"
      OTEL_PYTHON_LOG_FORMAT: "%(asctime)s | %(levelname)s | [%(name)s] | [%(filename)s:%(lineno)d] | %(message)s | [trace_id=%(otelTraceID)s span_id=%(otelSpanID)s resource.service.name=%(otelServiceName)s trace_sampled=%(otelTraceSampled)s]"
      OTEL_EXPORTER_OTLP_ENDPOINT: http://aws-otel-collector:4317
      # OTEL_EXPORTER_OTLP_LOGS_ENDPOINT: http://otel-collector:4317
      OTEL_SERVICE_NAME: "Local OpenTelemetry FastAPI Service"
      OTEL_LOG_LEVEL: "INFO"
      OTEL_TRACES_EXPORTER: "otlp" # "otlp,console" to export traces to console also
      OTEL_METRICS_EXPORTER: "otlp" # adding "console" will not filter and export all the metrics to console
      OTEL_LOGS_EXPORTER: "otlp,console"
    volumes:
      - ./:/app
    depends_on:
      - aws-otel-collector
      # - otel-collector
  
  # ADOT Collector
  # https://github.com/aws-observability/aws-otel-collector/blob/main/docs/developers/docker-demo.md
  # https://github.com/aws-observability/aws-otel-collector/blob/main/examples/docker/docker-compose.yaml
  aws-otel-collector:
    image: public.ecr.aws/aws-observability/aws-otel-collector:latest
    volumes:
      - ./otel-config.yaml:/etc/otel-agent-config.yaml
      # - ./:/app
    command: ["--config=/etc/otel-agent-config.yaml"]
    env_file:
      - .env
    ports:
      - 4317:4317 # OTLP gRPC receiver
      - 8888:8888
  
  logspout:
    # Logs: uses the docker daemon to collect logs from fastapi's stdout and push to cloudwatch
    image: mdsol/logspout:latest
    command: "cloudwatch://${AWS_REGION:-ap-south-1}?NOEC2" # default AWS_REGION to ap-south-1 if env var not set
    # command: "cloudwatch://${AWS_REGION}?DEBUG=1&NOEC2"  # use this line for verbose debug logs
    environment:
      EXCLUDE_LABELS: "logspout=disable"
      LOGSPOUT_GROUP: local-fastapi-otel-logs-loggroup
      LOGSPOUT_STREAM: "{{.Name}}"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    env_file:
      # aws credentials for pushing logs to cloudwatch
      - .env
    depends_on:
      - fastapi
      
  
  # # OpenTelemetry Collector
  # otel-collector:
  #   image: otel/opentelemetry-collector-contrib:latest
  #   volumes:
  #     - ./otel-config.yaml:/etc/otelcol-contrib/config.yaml
  #   # env_file:
  #   #   - .env
  #   ports:
  #     - 4317:4317 # OTLP gRPC receiver
  #     # - 4318:4318 # OTLP HTTP receiver
  #     - 8888:8888 # OTLP metrics receiver
  # #     # - 55679:55679 # zpages extension
