receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      # http:
      #   endpoint: 0.0.0.0:4318
  # aws xray reciever: https://aws-otel.github.io/docs/components/x-ray-receiver

exporters:
  # https://github.com/open-telemetry/opentelemetry-collector/tree/main/exporter/loggingexporter
  # https://github.com/open-telemetry/opentelemetry-collector/tree/main/exporter/debugexporter
  # Outputs telemetry data to the console for debugging purposes. "logging" is deprecated with "debug" exporter.
  logging:
    verbosity: normal

  # https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/awsemfexporter
  awsemf:
    region: ap-south-1
    output_destination: stdout
    # output_destination: cloudwatch
    log_group_name: local-fastapi-otel-emf-metric-loggroup
    # dimension_rollup_option: "NoDimensionRollup"
    namespace: local-fastapi-otel-namespace
    # resource_to_telemetry_conversion:
    #   # convert all the resource attributes to metric labels: THIS IS BAD, DIMENSION EXPLOSION
    #   enabled: true
    # metric_declarations:
    #   - dimensions: [[]]
    #     metric_name_selectors:
    #       # Export only custom metrics created in the FastAPI application
    #       - "^app.fastapi.*"

  # @TODO: Remove them later:
  # https://aws.amazon.com/blogs/mt/adding-metrics-and-traces-to-your-application-on-amazon-eks-with-aws-distro-for-opentelemetry-aws-x-ray-and-amazon-cloudwatch/
  # https://github.com/aws-samples/one-observability-demo/blob/main/PetAdoptions/petadoptionshistory-py/petadoptionshistory.py

  # https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/awscloudwatchlogsexporter
  awscloudwatchlogs:
    log_group_name: "local-fastapi-otel-logs-loggroup"
    log_stream_name: "local-fastapi-otel-logs-logstream"
    region: "ap-south-1"
    endpoint: "logs.ap-south-1.amazonaws.com"
    # raw_log: true # If set to true, only the log message will be exported to CloudWatch Logs. This needs to be set to true for EMF logs.

  # https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/exporter/awsxrayexporter/README.md
  # https://aws-otel.github.io/docs/getting-started/x-ray
  awsxray:
    region: ap-south-1
    aws_log_groups:
      [
        "local-fastapi-otel-emf-metric-loggroup",
        "local-fastapi-otel-logs-loggroup",
      ]
    # local_mode: true

# https://opentelemetry.io/docs/collector/transforming-telemetry/
processors:
  batch:
  filter:
    metrics:
      include:
        match_type: regexp
        metric_names:
          # Only include the custom metric
          - "^app.fastapi.*"

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [logging,awsxray]
    metrics:
      receivers: [otlp]
      processors: [filter]
      exporters: [logging,awsemf]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging,awscloudwatchlogs]

  # OpenTelemetry Internal Telemetry Configuration: https://opentelemetry.io/docs/collector/internal-telemetry/
  telemetry:
    # logs:
    #   level: ERROR
    #   development: true
    #   output_paths: ["stdout"]
    metrics:
      level: detailed
      address: 0.0.0.0:8888
