# https://opentelemetry.io/docs/languages/python/exporters/#prometheus

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

  # Prometheus Receiver: https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/prometheusreceiver
  prometheus:
    config:
      scrape_configs:
        - job_name: 'otelcol'
          scrape_interval: 10s
          static_configs:
            - targets: ['0.0.0.0:8888']

exporters:
  debug:
    verbosity: normal
  
  # Prometheus Exporter
  otlphttp/prometheus:
    endpoint: "http://prometheus:9090/api/v1/otlp"
    tls:
      insecure: true


service:
  pipelines:
    logs:
      receivers: [otlp]
      exporters: [debug]
    traces:
      receivers: [otlp]
      exporters: [debug]
    metrics:
      receivers: [otlp, prometheus]
      exporters: [debug, otlphttp/prometheus]
  
  # https://opentelemetry.io/docs/collector/internal-telemetry/#configure-internal-metrics
  # telemetry:
  #   metrics:
  #     level: normal
  #     # address: 0.0.0.0:8888
  #     readers:
  #       - pull:
  #           exporter:
  #             prometheus:
  #               host: '0.0.0.0'
  #               port: 8888
    # logs:
    #   level: ERROR
    #   development: true
    #   output_paths: ["stdout"]