global:
  evaluation_interval: 30s
  scrape_interval: 5s

storage:
  tsdb:
    out_of_order_time_window: 30m

scrape_configs:
  # - job_name: prometheus
  #   static_configs:
  #     - targets: ["localhost:9090"]

  - job_name: otel-collector
    static_configs:
      - targets: ["otelcol:8888"]
